/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: OPREXT (https://sketchfab.com/OPREXT)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vfx-explosion-724a9505d9974fca9e9cdac6e52e6f2f
Title: Vfx Explosion
*/

import { useGLTF } from '@react-three/drei';
import { BufferGeometry, Mesh } from 'three';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';
import { RefObject, useRef } from 'react';
import { RefProps } from '../common/props';

const Explosion = (props: RefProps) => {
  const { innerRef, ...rest } = props;
  const { nodes, materials } = useGLTF('/models/vfx_explosion.glb');
  const innerRefLocal = useRef<Mesh<BufferGeometry>>();
  const outerRef = useRef<Mesh<BufferGeometry>>();

  // continuosly spin
  useGSAP(() => {
    if (innerRefLocal.current) {
      gsap.timeline({ repeat: -1 }).to(innerRefLocal.current.rotation, {
        y: `+=${Math.PI * 2}`,
        x: `+=${Math.PI * 2}`,
        z: `+=${Math.PI * 2}`,
        ease: 'none',
        duration: 2.5
      });
      if (outerRef.current) {
        gsap.timeline({ repeat: -1 }).to(outerRef.current.rotation, {
          y: `-=${Math.PI * 2}`,
          x: `-=${Math.PI * 2}`,
          z: `-=${Math.PI * 2}`,
          ease: 'none',
          duration: 2.5
        });
      }
    }
  });

  return (
    <group {...rest} dispose={null} ref={innerRef}>
      <group
        position={[0.02197045, 0.10402713, -0.04289045]}
        rotation={[-2.09475399, -0.45316825, -2.71997209]}
        scale={1}
      >
        <mesh
          ref={outerRef as RefObject<Mesh<BufferGeometry>>}
          geometry={(nodes.Object_4 as Mesh).geometry}
          material={materials.material_0}
        />
        <mesh
          ref={innerRefLocal as RefObject<Mesh<BufferGeometry>>}
          geometry={(nodes.Object_5 as Mesh).geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
};

useGLTF.preload('/models/vfx_explosion.glb');

export default Explosion;
