/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BerserkerBroon (https://sketchfab.com/BerserkerBroon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-flask-dcf232cf9e964c478a1b2d59b8097510
Title: LowPoly - Flask
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'
import { RefProps } from '../common/RefProps'

const Flask = (props: RefProps) => {
  const { nodes, materials } = useGLTF('/models/lowpoly_-_flask.glb')
  return (
    <group {...props} dispose={null} ref={props.innerRef}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.6} position={[0,-1,0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cylinder_0 as Mesh).geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cylinder_1 as Mesh).geometry}
          material={materials.Cork}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cylinder_2 as Mesh).geometry}
          material={materials.Liquid}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/lowpoly_-_flask.glb');

export default Flask;

