/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jeremy E. Grayson (https://sketchfab.com/JeremyGrayson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pizza-23ddac5a352e488da455da7e6f3c3cb5
Title: Pizza
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three';
import { RefProps } from '../common/RefProps';

const Pizza = (props: RefProps) => {
  const { nodes, materials } = useGLTF('/models/pizza.glb');
  return (
    <group {...props} dispose={null} scale={0.4} ref={props.innerRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_2 as Mesh).geometry}
        material={materials['Material.001']}
        rotation={[-Math.PI / 3, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/pizza.glb');

export default Pizza;