/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: roroer (https://sketchfab.com/roroer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-tree-6ba26deef34249ddb8694888b47db449
Title: Stylized tree
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'
import { RefProps } from '../common/RefProps'

const StylizedTree = (props: RefProps) => {
  const { nodes, materials } = useGLTF('/models/stylized_tree.glb')
  return (
    <group {...props} dispose={null} ref={props.innerRef}>
      <group rotation={[-Math.PI / 2, 0, 0]}  scale={0.004}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Tree_base_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder001_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder002_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder004_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder005_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder006_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder007_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder008_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder009_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/stylized_tree.glb');

export default StylizedTree;
