/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LowSeb (https://sketchfab.com/lowseb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-sword-da574cba504e4b83a3293f3d3bd067fb
Title: medieval sword
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'
import { HobbyObjectProps } from '../common/props'

const Sword = (props: HobbyObjectProps) => {
  const { nodes, materials } = useGLTF('/models/medieval_sword.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.defaultMaterial as Mesh).geometry}
          material={materials.wire_135059008}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh visible={!!props.emissive}
          geometry={(nodes.defaultMaterial as Mesh).geometry}
          material={materials.wire_135059008}
          rotation={[Math.PI, 0, 0]}
          >
          <meshStandardMaterial opacity={0.5} color={'blue'} emissive={'blue'} emissiveIntensity={1} transparent/> 
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/medieval_sword.glb')

export default Sword;
