/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pixelgrapher (https://sketchfab.com/pixelgrapher)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-pixelart-anvil-40d7aa59f24e49da99be1d4dd5fda8e5
Title: Lowpoly Pixelart Anvil
*/

import { useGLTF } from '@react-three/drei';
import { Mesh } from 'three';
import { HobbyObjectProps } from '../../common/props';


const Anvil = (props: HobbyObjectProps) => {
  const { nodes, materials } = useGLTF('/models/lowpoly_pixelart_anvil.glb')
  return (
    <group {...props} dispose={null} scale={0.1}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.anvil2_anvilBlinn_MAT_0 as Mesh).geometry}
        material={materials.anvilBlinn_MAT}
        scale={[1, 1, 1.1]}
      />
      <mesh visible={!!props.emissive}
        castShadow
        receiveShadow
        geometry={(nodes.anvil2_anvilBlinn_MAT_0 as Mesh).geometry}
        material={materials.anvilBlinn_MAT}
        scale={[1, 1, 1.1]}
      >
        <meshStandardMaterial opacity={0.5} color={'blue'} emissive={'blue'} emissiveIntensity={1} transparent/>
      </mesh>
    </group>
  )
};

//useGLTF.preload('/models/lowpoly_pixelart_anvil.glb');

export default Anvil;