/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: afurokn (https://sketchfab.com/afurokn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basketball-2343abdae7674f46ad85071858db93c6
Title: Basketball
*/

import { useGLTF } from '@react-three/drei';
import { HobbyObjectProps } from '../../common/props';
import { Mesh } from 'three';

const Basketball = (props: HobbyObjectProps) => {
  const { nodes, materials } = useGLTF('/models/basketball.glb');
  return (
    <group {...props} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.3} ref={props.callback}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Basketball_0 as Mesh).geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Basketball_1 as Mesh).geometry}
          material={materials['Material.001']}
        />
        <mesh visible={!!props.emissive}
          geometry={(nodes.Basketball_0 as Mesh).geometry}
          material={materials.Material}
        >
          <meshStandardMaterial opacity={0.5} color={'blue'} emissive={'blue'} emissiveIntensity={1} transparent/> 
        </mesh>
      </group>
    </group>
  )
};

//useGLTF.preload('/models/basketball.glb');

export default Basketball;
