/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LastPain (https://sketchfab.com/LastPain)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-pizza-e6728d6e345a433191d0f02dd61bf137
Title: Cartoon Pizza
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'
import { HobbyObjectProps } from '../../common/props'


const Pizza = (props: HobbyObjectProps) => {
  const { nodes, materials } = useGLTF('/models/cartoon_pizza.glb')
  return (
    <group {...props} dispose={null} scale={2.2}>
      <group rotation={[-Math.PI / 2.5, 0, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_2 as Mesh).geometry}
          material={materials.Material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_3 as Mesh).geometry}
          material={materials.Material_0}
        />
        <mesh visible={!!props.emissive}
        castShadow
        receiveShadow
        geometry={(nodes.Object_3 as Mesh).geometry}
        material={materials.Material_0}
        >
          <meshStandardMaterial opacity={0.5} color={'blue'} emissive={'blue'} emissiveIntensity={1} transparent/>
        </mesh>
      </group>
    </group>
  )
}


useGLTF.preload('/models/cartoon_pizza.glb')


export default Pizza;