/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: roroer (https://sketchfab.com/roroer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-tree-6ba26deef34249ddb8694888b47db449
Title: Stylized tree
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'
import { HobbyObjectProps } from '../../common/props'

const StylizedTree = (props: HobbyObjectProps) => {
  const { nodes, materials } = useGLTF('/models/stylized_tree.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI]} position={[0,-1,0]} scale={0.0035}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Tree_base_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder001_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder002_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder004_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder005_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder006_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder007_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder008_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cylinder009_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh visible={!!props.emissive}
            geometry={(nodes.Tree_base_Material001_0 as Mesh).geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <meshStandardMaterial opacity={0.5} color={'blue'} emissive={'blue'} emissiveIntensity={1} transparent/> 
          </mesh>
        </group>
      </group>
    </group>
  )
}

//useGLTF.preload('/models/stylized_tree.glb');

export default StylizedTree;
